name: Concurrency # Name of your workflow

on: [push] # The event that triggers the workflow

jobs: 
  hello: # The ID of the job
    runs-on: ubuntu-latest # The runner environment
    steps:
      - name: step1 # Name of the first step
        run: echo "Hello World"